### PR TITLE
Added support for Google Analytics

### PR DESCRIPTION
**Pull request by OpenSourceZombie**
add support for google analytics in our website

### CODE REVIEW

**Comment by a3f** [comment]
@KarimAllah Don't hijack other people's commits. That's impolite!
@OpenSourceZombie Whose Google account is that?

**Comment by OpenSourceZombie** [comment]
> @OpenSourceZombie Whose Google account is that?

@a3f osdev4arab's

**Comment by a3f** [comment]
Merged. Thanks.

**Comment by KarimAllah** [comment]
@a3f other people's commits ? What are you talking about ?

**Comment by a3f** [comment]
Maybe I misunderstood something. Why was this commit ( https://github.com/OpenSourceZombie/osdev4arab.github.io/commit/143ffba4c0402b15a50cdc209361d1609803eda6 ) part of the patch?

**Comment by KarimAllah** [comment]
Not it was not supposed to be part of the pull request, and even if it's it has me as an 'Author'!

I pushed the commit then I amended it, then I force pushed it again. I was mostly testing the the DNS server CNAME stuff. I assumed since the window between the original push and this push amended push was very small there's no chance that anybody would have pulled/cloned the repository meanwhile! Apparently I was wrong.

He must have pulled the master branch, based his work on top of that and then created the pull request. Since git don't track the relationship between an amended commit and the original commit, it assumed that the original commit was actually a new commit that's why when he created the pull request it was there.

So, no I didn't Hijack a commit and it was actually obvious from the Author in this commit!

Anyway, two important lessons learned here:
- Force push should be banned, and if you received a pull request with a conflict .. please don't try to fix it yourself. Ask the requester to fix it.
- Don't make bold statements like "That's impolite" based on a wrong guess. Actually don't make them at all, please. We don't want to make the community think that they are allowed to judge each other this way. If you really want to make a statement at least use a more polite negative form, like "that's not very polite", etc! (I would recommend not doing that altogether)

**Comment by a3f** [comment]
I agree with first point. As for the second point, I didn't mean to be condescending in any way. Sorry to have given you that impression.

**Pull request merged**
